[workspace]
members = ["crates/*", "native-host", "zkvm-client", "zkvm-host"]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
authors = ["zachobront"]
homepage = ""
repository = ""

[workspace.dependencies]

# kona
kona-common = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
kona-common-proc = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
kona-preimage = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream", features = [
    "rkyv",
] }
kona-primitives = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
kona-mpt = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
kona-derive = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream", default-features = false }
kona-executor = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
kona-client = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }

# general
anyhow = { version = "1.0.86", default-features = false }
cfg-if = "1.0.0"
spin = { version = "0.9.8", features = ["mutex"] }
lru = "0.12.3"
async-trait = "0.1.80"
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2", default-features = false, features = [
    "compress",
] }
tokio = { version = "1.37.0", features = ["full"] }
clap = "4.5.9"
cargo_metadata = "0.18.1"

# serialization
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.117", default-features = false }
rkyv = "0.7.44"
hex = "0.4.3"

# local
client-utils = { path = "crates/client" }
host-utils = { path = "crates/host" }
zkvm-client = { path = "zkvm-client" }
zkvm-host = { path = "zkvm-host" }

# ethereum
# Note: Using ethers instead of alloy because kona-host depends on alloy-primitives, which causes
# dependency conflicts when resolving alloy-primitives from alloy crate instead of standalone alloy-primitives.
# Once kona-host moves to using the new alloy, we can use alloy instead of ethers.
ethers = { version = "2.0" }
alloy = { version = "0.1", default-features = false }
alloy-primitives = { version = "0.7.6", default-features = false }
alloy-rlp = { version = "0.3.5", default-features = false }
alloy-consensus = { version = "0.1", default-features = false }
alloy-sol-types = { version = "0.7.6" }
kona-host = { git = "https://github.com/moongate-forks/kona/", branch = "new-upstream" }
alloy-eips = { version = "0.1", default-features = false }
revm = { git = "https://github.com/bluealloy/revm", tag = "v37", version = "10.0.0", default-features = false }

# sp1
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }

[profile.release-client-lto]
inherits = "release"
panic = "abort"
codegen-units = 1
lto = "fat"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2", default-features = false, features = [
    "compress",
] }
