[package]
name = "zkvm-client"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]

# workspace (general)
cfg-if.workspace = true
anyhow.workspace = true
async-trait.workspace = true
rkyv.workspace = true
sha2.workspace = true

# workspace (ethereum)
alloy-primitives.workspace = true
alloy-consensus.workspace = true

# workspace (kona)
kona-preimage.workspace = true
kona-primitives.workspace = true
kona-executor.workspace = true
kona-client.workspace = true

# workspace (local)
client-utils.workspace = true

# sp1
sp1-zkvm = { workspace = true }

[dev-dependencies]
