[package]
name = "zkvm-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "single"
path = "bin/single.rs"

[[bin]]
name = "fetch_and_save_proof"
path = "bin/fetch_and_save_proof.rs"

[[bin]]
name = "multi"
path = "bin/multi.rs"

[[bin]]
name = "agg"
path = "bin/agg.rs"

[[bin]]
name = "server"
path = "bin/server.rs"

[dependencies]

# workspace
tokio = { workspace = true }
clap = { workspace = true }
cargo_metadata = { workspace = true }
alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }

# kona
kona-host = { workspace = true }

# local
host-utils.workspace = true

# sp1
sp1-sdk = { workspace = true }
anyhow.workspace = true
dotenv.workspace = true
num-format.workspace = true
revm.workspace = true
client-utils.workspace = true
serde = { workspace = true }

# server
axum = { version = "0.7.4", features = ["macros"]  }
bincode.workspace = true
futures.workspace = true
serde_cbor.workspace = true
log.workspace = true
hex.workspace = true
tower-http = { version = "0.5.2", features = ["limit"] }
base64 = "0.22.1"

[build-dependencies]
sp1-helper = { workspace = true }
